### ISSUE TITLE
this line is ok ? "self"

### ISSUE THREAD

**Issue by liyingkun1237** [johannespetrat/HyperparameterOptimisation#11]
https://github.com/johannespetrat/OptML/blob/6e22487c310b36f68ebab122518ca545fd3abff9/optml/gridsearch_optimizer.py#L32

**Comment by johannespetrat** [comment]
Hi liyingkun1237,
yes, this should be correct. Every optimizer object has attributes for parameters to optimize, the model, and an evaluation function to be maximized. 
Did you encounter any errors running this?

**Comment by johannespetrat** [comment]
Closing this as it's not an issue. Please raise another issue if you encountered a specific problem.
