### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by Erotemic** [johannespetrat/HyperparameterOptimisation#2]
Two issues prevented me from installing and then importing this module. 

In `setup.py` README.rst should be README.md 

in `random_search.py` `from models import Model` should be `from .models import Model`

in bayesian_optimizer.py, `   xs = np.array([params.values()  for score, params in self.hyperparam_history])` should wrap `params.values()` with list for python3 support

Also, in general there seems to be a lot of unused variables and imports. 

If I end up getting this to work well, I'll make a PR because I like the wrapper interface this module provides.

**Comment by johannespetrat** [comment]
Hi Erotemic, thanks for trying out the package and for raising this issue. I just got back from vacation and will create a PR with fixes as soon as possible!
