### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-j1whj9uc/optml/README.md'

### ISSUE THREAD

**Issue by eyadsibai** [johannespetrat/HyperparameterOptimisation#8]
https://github.com/johannespetrat/OptML/blob/3c3bc5927f793b2d7600ecd8294422cce9fbc051/setup.py#L18

I am getting the following error when I try to install optml
```
file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-j1whj9uc/optml/README.md'
```

**Comment by johannespetrat** [comment]
Hi, this PR #9  should fix this. Turns out the README.md is not automatically included on PyPi. Please let me know if `pip install optml` now works for you.

**Comment by johannespetrat** [comment]
OptML now installs correctly in python 2 and 3, so i'll close this issue. Please let me know if your issue persists.

**Comment by eyadsibai** [comment]
:+1: it works for me
